# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'zjz' do
 pod 'JZFramework', :git => 'https://github.com/zengjinzong/JZFramework.git'
 # :path => '../'
 #https://github.com/zengjinzong/JZFramework.git

end
